### PR TITLE
added save/load matlab using external library

### PR DESCRIPTION
**Pull request by ennerf**
See #132 for discussion. This does the simplest thing and stores/loads a single variable using the default settings (compressed).

### CODE REVIEW

**Comment by lessthanoptimal** [comment]
Have you tested this yet in a project that's missing the dependency? Does `MatrixIO` blow up because of the import statements?

**Comment by ennerf** [comment]
`compileOnly` doesn't add it to the test runtime, so the unit test verifies the failing case.

I've used similar patterns a few times, e.g., for choosing a Java 8 vs 11 implementation at runtime. The nested class usages get moved into a separate `.class` file during during compilation, so the Classloader won't try to load the library until the nested class gets used. Doing it this way plays nicer with obfuscation tools like ProGuard (and presumably Graal's native image?), and has no associated performance cost compared to a normally compiled version.

**Comment by lessthanoptimal** [comment]
Sorry for taking a bit to review this. When I run locally on my home computer a unit test is failing. `load_save_matlab_missing_dep_msg()`

```
org.opentest4j.AssertionFailedError: Expected java.lang.IllegalStateException to be thrown, but nothing was thrown.
...
at org.ejml.ops.TestMatrixIO.load_save_matlab_missing_dep_msg(TestMatrixIO.java:101)
```

**Comment by lessthanoptimal** [comment]
I ran into no issues when calling it from another project without your lib.

**Comment by ennerf** [comment]
Interesting. Building/testing it with the Gradle wrapper worked for me just fine. Can you give me any more information about how you were running the tests?

By no issues, do you mean that you ran `saveMatlab` without MFL on the path and it didn't throw any errors?

**Comment by lessthanoptimal** [comment]
Appears to be an intellij issue. Gradle is the official criteria so it passes! Could you just squash the commit then feel free to merge.

**Review by lessthanoptimal — APPROVED** [review]
LGTM squash then merge. Thanks!

**Comment by ennerf** [comment]
Sounds good 👍. I don't have write access to do a (squash) merge, so I'm assuming that you'd be doing that?

image

Running the tests in IntelliJ worked for me as well. Maybe it needs to clean and/or re-synchronize the project

**Comment by lessthanoptimal** [comment]
yeah I tried reloading gradle immediately when I had that issue. One difference could be that I have IntelliJ run tests directly and not through Gradle since it's much faster.

**Pull request merged**
