### PR TITLE
feature/concurrent_dscc

### PR DESCRIPTION
**Pull request by lessthanoptimal**
- First pass at adding a concurrent implementation of mult for DSCC

### CODE REVIEW

**Comment by lessthanoptimal** [comment]
@szarnyasg  @FlorentinD thought you two might be interested in this. Was able to quickly implement a concurrent sparse matrix multiplication. I'm getting about a 1.9x speed up on 4-core computer.

**Comment by FlorentinD** [comment]
That’s sounds awesome :) 

I think it would be very useful, if the user could specify the used concurrency.
Maybe as a global option. 
In this case the system could also decide on its own, which implementation to use.

**Comment by lessthanoptimal** [comment]
That's the plan, but I might wait until the next release. A lot of code to hook that into and tests to make sure it's done right. I would like to have a new stable release out soon so I need to stop doing massive changes to the code.

In a real-world application this new concurrency code speed it up from  3.3 min to 1 min.

**Comment by FlorentinD** [comment]
Looking forward to it:)

**Comment by lessthanoptimal** [comment]
Right now there's only concurrent add(s,s,s) and mult(s,s,s). Going to look into adding concurrent versions of sparse-dense mult(). There might be hope of making QR partially concurrent without a completely new algorithm.

**Pull request closed without merging**
