### PR TITLE
Fix docstring typos

### PR DESCRIPTION
**Pull request by JozsefKutas**
Various docstring fixes, mostly where the documented bits (32/64) were wrong.

### CODE REVIEW

**Comment by JozsefKutas** [comment]
I'm getting a CI failure, but I think it's due to the recent update to use Java 17. When I run `./gradlew spotlessJavaApply` locally, it works with Java 11, but not with Java 17.

**Review by lessthanoptimal — COMMENTED** [review]
Looks good! Going to see why spotless isn't happy now.

**Comment by lessthanoptimal** [comment]
Created new PR https://github.com/lessthanoptimal/ejml/pull/162 that updates spotless and fixes that issue.

**Comment by lessthanoptimal** [comment]
Merged with the other PR. Thanks!

**Pull request closed without merging**
